#ifndef SCOTT_PLATFORM_WINDOWS_H
#define SCOTT_PLATFORM_WINDOWS_H

#include "stdafx.h"

LRESULT CALLBACK	WndProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK	DlgWndProc(HWND, UINT, WPARAM, LPARAM);

#endif